console.log('console.log(5/0)')
console.log(5/0)
console.log('')
console.log('console.log(2**1024)')
console.log(2**1024)
console.log('console.log(2**1023)')
console.log(2**1023)
console.log('')
console.log('console.log(-(2**1024))')
console.log(-(2**1024))
console.log('')
console.log('console.log(-5/0)')
console.log(-5/0)
console.log('')
console.log(typeof NaN)
console.log('hello'*2)
NaN == NaN