let s = 'hello'
console.log(s.slice(1,3))
console.log(s.substring(1,3))
console.log(s.slice(1))
console.log(s.substring(1))
console.log(s.slice())
console.log(s.substring())
console.log(s.slice(-3,-1))
console.log(s.substring(-3,-1))
console.log(s.substr(2,3))
console.log(s.split('e'))
console.log(s.split(''))
console.log(s.split('', 2))